[phases.setup]
nixPkgs = [
  "chromium",
  "glib",
  "libglib",
  "nss",
  "atk",
  "gtk3",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "libgbm",
  "libxss",
  "libasound",
  "alsa-lib",
  "libx11",
  "libxtst",
  "libxcb"
]

[phases.build]
cmds = ["npm ci --omit=dev"]

[phases.production]
cmds = ["npm start"]
